//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.wsAcompUAU {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", ConfigurationName="wsAcompUAU.wsAcompanhamentosServicosSoap")]
    public interface wsAcompanhamentosServicosSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento obra no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoOrcado", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse AcompanharServicoOrcado(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoOrcado", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse> AcompanharServicoOrcadoAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento obra no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoContrato", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse AcompanharServicoContrato(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoContrato", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse> AcompanharServicoContratoAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento empresa no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoPL", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse AcompanharServicoPL(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/AcompanharServicoPL", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse> AcompanharServicoPLAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento empresa no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coPL", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse ExcluirAcompanhamentoServicoPL(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coPL", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse> ExcluirAcompanhamentoServicoPLAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento obra no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coOrcado", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse ExcluirAcompanhamentoServicoOrcado(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coOrcado", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse> ExcluirAcompanhamentoServicoOrcadoAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento servico no namespace http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coDeContrato", ReplyAction="*")]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse ExcluirAcompanhamentoServicoDeContrato(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos/ExcluirAcompanhamentoServi" +
            "coDeContrato", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse> ExcluirAcompanhamentoServicoDeContratoAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoOrcadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoOrcado", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequestBody Body;
        
        public AcompanharServicoOrcadoRequest() {
        }
        
        public AcompanharServicoOrcadoRequest(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoOrcadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int orcamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string periodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double quantidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string usuarioLogado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sequencia;
        
        public AcompanharServicoOrcadoRequestBody() {
        }
        
        public AcompanharServicoOrcadoRequestBody(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string usuarioLogado, string sequencia) {
            this.empresa = empresa;
            this.obra = obra;
            this.servico = servico;
            this.item = item;
            this.orcamento = orcamento;
            this.periodo = periodo;
            this.quantidade = quantidade;
            this.usuarioLogado = usuarioLogado;
            this.sequencia = sequencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoOrcadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoOrcadoResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponseBody Body;
        
        public AcompanharServicoOrcadoResponse() {
        }
        
        public AcompanharServicoOrcadoResponse(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoOrcadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcompanharServicoOrcadoResult;
        
        public AcompanharServicoOrcadoResponseBody() {
        }
        
        public AcompanharServicoOrcadoResponseBody(string AcompanharServicoOrcadoResult) {
            this.AcompanharServicoOrcadoResult = AcompanharServicoOrcadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoContrato", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequestBody Body;
        
        public AcompanharServicoContratoRequest() {
        }
        
        public AcompanharServicoContratoRequest(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoContratoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int contratoServico;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int itemContrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string dataFim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mesPl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double quantidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double porcentagemAcomp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string observacoes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string etapa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string codEstrutura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string sequencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string usuarioLogado;
        
        public AcompanharServicoContratoRequestBody() {
        }
        
        public AcompanharServicoContratoRequestBody(int empresa, string obra, int contratoServico, int itemContrato, string servico, string dataInicio, string dataFim, string mesPl, double quantidade, double porcentagemAcomp, string observacoes, string etapa, string codEstrutura, string sequencia, string usuarioLogado) {
            this.empresa = empresa;
            this.obra = obra;
            this.contratoServico = contratoServico;
            this.itemContrato = itemContrato;
            this.servico = servico;
            this.dataInicio = dataInicio;
            this.dataFim = dataFim;
            this.mesPl = mesPl;
            this.quantidade = quantidade;
            this.porcentagemAcomp = porcentagemAcomp;
            this.observacoes = observacoes;
            this.etapa = etapa;
            this.codEstrutura = codEstrutura;
            this.sequencia = sequencia;
            this.usuarioLogado = usuarioLogado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoContratoResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponseBody Body;
        
        public AcompanharServicoContratoResponse() {
        }
        
        public AcompanharServicoContratoResponse(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoContratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcompanharServicoContratoResult;
        
        public AcompanharServicoContratoResponseBody() {
        }
        
        public AcompanharServicoContratoResponseBody(string AcompanharServicoContratoResult) {
            this.AcompanharServicoContratoResult = AcompanharServicoContratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoPLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoPL", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequestBody Body;
        
        public AcompanharServicoPLRequest() {
        }
        
        public AcompanharServicoPLRequest(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoPLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int produto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double qtde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sequencia;
        
        public AcompanharServicoPLRequestBody() {
        }
        
        public AcompanharServicoPLRequestBody(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            this.empresa = empresa;
            this.obra = obra;
            this.produto = produto;
            this.contrato = contrato;
            this.item = item;
            this.servico = servico;
            this.mes = mes;
            this.usuario = usuario;
            this.qtde = qtde;
            this.sequencia = sequencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcompanharServicoPLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcompanharServicoPLResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponseBody Body;
        
        public AcompanharServicoPLResponse() {
        }
        
        public AcompanharServicoPLResponse(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class AcompanharServicoPLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcompanharServicoPLResult;
        
        public AcompanharServicoPLResponseBody() {
        }
        
        public AcompanharServicoPLResponseBody(string AcompanharServicoPLResult) {
            this.AcompanharServicoPLResult = AcompanharServicoPLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoPLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoPL", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequestBody Body;
        
        public ExcluirAcompanhamentoServicoPLRequest() {
        }
        
        public ExcluirAcompanhamentoServicoPLRequest(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoPLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int produto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double qtde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sequencia;
        
        public ExcluirAcompanhamentoServicoPLRequestBody() {
        }
        
        public ExcluirAcompanhamentoServicoPLRequestBody(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            this.empresa = empresa;
            this.obra = obra;
            this.produto = produto;
            this.contrato = contrato;
            this.item = item;
            this.servico = servico;
            this.mes = mes;
            this.usuario = usuario;
            this.qtde = qtde;
            this.sequencia = sequencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoPLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoPLResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponseBody Body;
        
        public ExcluirAcompanhamentoServicoPLResponse() {
        }
        
        public ExcluirAcompanhamentoServicoPLResponse(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoPLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExcluirAcompanhamentoServicoPLResult;
        
        public ExcluirAcompanhamentoServicoPLResponseBody() {
        }
        
        public ExcluirAcompanhamentoServicoPLResponseBody(string ExcluirAcompanhamentoServicoPLResult) {
            this.ExcluirAcompanhamentoServicoPLResult = ExcluirAcompanhamentoServicoPLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoOrcadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoOrcado", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequestBody Body;
        
        public ExcluirAcompanhamentoServicoOrcadoRequest() {
        }
        
        public ExcluirAcompanhamentoServicoOrcadoRequest(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoOrcadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int orcamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string periodo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double quantidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sequencia;
        
        public ExcluirAcompanhamentoServicoOrcadoRequestBody() {
        }
        
        public ExcluirAcompanhamentoServicoOrcadoRequestBody(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string sequencia) {
            this.empresa = empresa;
            this.obra = obra;
            this.servico = servico;
            this.item = item;
            this.orcamento = orcamento;
            this.periodo = periodo;
            this.quantidade = quantidade;
            this.sequencia = sequencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoOrcadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoOrcadoResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponseBody Body;
        
        public ExcluirAcompanhamentoServicoOrcadoResponse() {
        }
        
        public ExcluirAcompanhamentoServicoOrcadoResponse(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoOrcadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExcluirAcompanhamentoServicoOrcadoResult;
        
        public ExcluirAcompanhamentoServicoOrcadoResponseBody() {
        }
        
        public ExcluirAcompanhamentoServicoOrcadoResponseBody(string ExcluirAcompanhamentoServicoOrcadoResult) {
            this.ExcluirAcompanhamentoServicoOrcadoResult = ExcluirAcompanhamentoServicoOrcadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoDeContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoDeContrato", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequestBody Body;
        
        public ExcluirAcompanhamentoServicoDeContratoRequest() {
        }
        
        public ExcluirAcompanhamentoServicoDeContratoRequest(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoDeContratoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int contratoServico;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int itemContrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string servico;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double quantidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sequencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigoEstrutura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string usuarioLogado;
        
        public ExcluirAcompanhamentoServicoDeContratoRequestBody() {
        }
        
        public ExcluirAcompanhamentoServicoDeContratoRequestBody(int empresa, int contratoServico, int itemContrato, string servico, double quantidade, string sequencia, string codigoEstrutura, string usuarioLogado) {
            this.empresa = empresa;
            this.contratoServico = contratoServico;
            this.itemContrato = itemContrato;
            this.servico = servico;
            this.quantidade = quantidade;
            this.sequencia = sequencia;
            this.codigoEstrutura = codigoEstrutura;
            this.usuarioLogado = usuarioLogado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirAcompanhamentoServicoDeContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirAcompanhamentoServicoDeContratoResponse", Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos", Order=0)]
        public WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponseBody Body;
        
        public ExcluirAcompanhamentoServicoDeContratoResponse() {
        }
        
        public ExcluirAcompanhamentoServicoDeContratoResponse(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/UAUWeb_WS/wsAcompanhamentosServicos")]
    public partial class ExcluirAcompanhamentoServicoDeContratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExcluirAcompanhamentoServicoDeContratoResult;
        
        public ExcluirAcompanhamentoServicoDeContratoResponseBody() {
        }
        
        public ExcluirAcompanhamentoServicoDeContratoResponseBody(string ExcluirAcompanhamentoServicoDeContratoResult) {
            this.ExcluirAcompanhamentoServicoDeContratoResult = ExcluirAcompanhamentoServicoDeContratoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAcompanhamentosServicosSoapChannel : WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAcompanhamentosServicosSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap>, WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap {
        
        public wsAcompanhamentosServicosSoapClient() {
        }
        
        public wsAcompanhamentosServicosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAcompanhamentosServicosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAcompanhamentosServicosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAcompanhamentosServicosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoOrcado(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest request) {
            return base.Channel.AcompanharServicoOrcado(request);
        }
        
        public string AcompanharServicoOrcado(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string usuarioLogado, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.servico = servico;
            inValue.Body.item = item;
            inValue.Body.orcamento = orcamento;
            inValue.Body.periodo = periodo;
            inValue.Body.quantidade = quantidade;
            inValue.Body.usuarioLogado = usuarioLogado;
            inValue.Body.sequencia = sequencia;
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoOrcado(inValue);
            return retVal.Body.AcompanharServicoOrcadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoOrcadoAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest request) {
            return base.Channel.AcompanharServicoOrcadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoResponse> AcompanharServicoOrcadoAsync(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string usuarioLogado, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoOrcadoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.servico = servico;
            inValue.Body.item = item;
            inValue.Body.orcamento = orcamento;
            inValue.Body.periodo = periodo;
            inValue.Body.quantidade = quantidade;
            inValue.Body.usuarioLogado = usuarioLogado;
            inValue.Body.sequencia = sequencia;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoOrcadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoContrato(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest request) {
            return base.Channel.AcompanharServicoContrato(request);
        }
        
        public string AcompanharServicoContrato(int empresa, string obra, int contratoServico, int itemContrato, string servico, string dataInicio, string dataFim, string mesPl, double quantidade, double porcentagemAcomp, string observacoes, string etapa, string codEstrutura, string sequencia, string usuarioLogado) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.contratoServico = contratoServico;
            inValue.Body.itemContrato = itemContrato;
            inValue.Body.servico = servico;
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            inValue.Body.mesPl = mesPl;
            inValue.Body.quantidade = quantidade;
            inValue.Body.porcentagemAcomp = porcentagemAcomp;
            inValue.Body.observacoes = observacoes;
            inValue.Body.etapa = etapa;
            inValue.Body.codEstrutura = codEstrutura;
            inValue.Body.sequencia = sequencia;
            inValue.Body.usuarioLogado = usuarioLogado;
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoContrato(inValue);
            return retVal.Body.AcompanharServicoContratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoContratoAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest request) {
            return base.Channel.AcompanharServicoContratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoResponse> AcompanharServicoContratoAsync(int empresa, string obra, int contratoServico, int itemContrato, string servico, string dataInicio, string dataFim, string mesPl, double quantidade, double porcentagemAcomp, string observacoes, string etapa, string codEstrutura, string sequencia, string usuarioLogado) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoContratoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.contratoServico = contratoServico;
            inValue.Body.itemContrato = itemContrato;
            inValue.Body.servico = servico;
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            inValue.Body.mesPl = mesPl;
            inValue.Body.quantidade = quantidade;
            inValue.Body.porcentagemAcomp = porcentagemAcomp;
            inValue.Body.observacoes = observacoes;
            inValue.Body.etapa = etapa;
            inValue.Body.codEstrutura = codEstrutura;
            inValue.Body.sequencia = sequencia;
            inValue.Body.usuarioLogado = usuarioLogado;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoContratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoPL(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest request) {
            return base.Channel.AcompanharServicoPL(request);
        }
        
        public string AcompanharServicoPL(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.produto = produto;
            inValue.Body.contrato = contrato;
            inValue.Body.item = item;
            inValue.Body.servico = servico;
            inValue.Body.mes = mes;
            inValue.Body.usuario = usuario;
            inValue.Body.qtde = qtde;
            inValue.Body.sequencia = sequencia;
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoPL(inValue);
            return retVal.Body.AcompanharServicoPLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.AcompanharServicoPLAsync(WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest request) {
            return base.Channel.AcompanharServicoPLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLResponse> AcompanharServicoPLAsync(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest inValue = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.AcompanharServicoPLRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.produto = produto;
            inValue.Body.contrato = contrato;
            inValue.Body.item = item;
            inValue.Body.servico = servico;
            inValue.Body.mes = mes;
            inValue.Body.usuario = usuario;
            inValue.Body.qtde = qtde;
            inValue.Body.sequencia = sequencia;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).AcompanharServicoPLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoPL(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoPL(request);
        }
        
        public string ExcluirAcompanhamentoServicoPL(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.produto = produto;
            inValue.Body.contrato = contrato;
            inValue.Body.item = item;
            inValue.Body.servico = servico;
            inValue.Body.mes = mes;
            inValue.Body.usuario = usuario;
            inValue.Body.qtde = qtde;
            inValue.Body.sequencia = sequencia;
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoPL(inValue);
            return retVal.Body.ExcluirAcompanhamentoServicoPLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoPLAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoPLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLResponse> ExcluirAcompanhamentoServicoPLAsync(string empresa, string obra, int produto, int contrato, string item, string servico, string mes, string usuario, double qtde, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoPLRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.produto = produto;
            inValue.Body.contrato = contrato;
            inValue.Body.item = item;
            inValue.Body.servico = servico;
            inValue.Body.mes = mes;
            inValue.Body.usuario = usuario;
            inValue.Body.qtde = qtde;
            inValue.Body.sequencia = sequencia;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoPLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoOrcado(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoOrcado(request);
        }
        
        public string ExcluirAcompanhamentoServicoOrcado(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.servico = servico;
            inValue.Body.item = item;
            inValue.Body.orcamento = orcamento;
            inValue.Body.periodo = periodo;
            inValue.Body.quantidade = quantidade;
            inValue.Body.sequencia = sequencia;
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoOrcado(inValue);
            return retVal.Body.ExcluirAcompanhamentoServicoOrcadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoOrcadoAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoOrcadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoResponse> ExcluirAcompanhamentoServicoOrcadoAsync(int empresa, string obra, string servico, string item, int orcamento, string periodo, double quantidade, string sequencia) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoOrcadoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.obra = obra;
            inValue.Body.servico = servico;
            inValue.Body.item = item;
            inValue.Body.orcamento = orcamento;
            inValue.Body.periodo = periodo;
            inValue.Body.quantidade = quantidade;
            inValue.Body.sequencia = sequencia;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoOrcadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoDeContrato(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoDeContrato(request);
        }
        
        public string ExcluirAcompanhamentoServicoDeContrato(int empresa, int contratoServico, int itemContrato, string servico, double quantidade, string sequencia, string codigoEstrutura, string usuarioLogado) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.contratoServico = contratoServico;
            inValue.Body.itemContrato = itemContrato;
            inValue.Body.servico = servico;
            inValue.Body.quantidade = quantidade;
            inValue.Body.sequencia = sequencia;
            inValue.Body.codigoEstrutura = codigoEstrutura;
            inValue.Body.usuarioLogado = usuarioLogado;
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse retVal = ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoDeContrato(inValue);
            return retVal.Body.ExcluirAcompanhamentoServicoDeContratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse> WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap.ExcluirAcompanhamentoServicoDeContratoAsync(WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest request) {
            return base.Channel.ExcluirAcompanhamentoServicoDeContratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoResponse> ExcluirAcompanhamentoServicoDeContratoAsync(int empresa, int contratoServico, int itemContrato, string servico, double quantidade, string sequencia, string codigoEstrutura, string usuarioLogado) {
            WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest inValue = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequest();
            inValue.Body = new WindowsFormsApp2.wsAcompUAU.ExcluirAcompanhamentoServicoDeContratoRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.contratoServico = contratoServico;
            inValue.Body.itemContrato = itemContrato;
            inValue.Body.servico = servico;
            inValue.Body.quantidade = quantidade;
            inValue.Body.sequencia = sequencia;
            inValue.Body.codigoEstrutura = codigoEstrutura;
            inValue.Body.usuarioLogado = usuarioLogado;
            return ((WindowsFormsApp2.wsAcompUAU.wsAcompanhamentosServicosSoap)(this)).ExcluirAcompanhamentoServicoDeContratoAsync(inValue);
        }
    }
}
